apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1 # number of pods to create
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      # This is the same as the container spec in client-pod.yaml
      containers:
        - name: client
          image: stephengrider/multi-client
          ports:
            - containerPort: 3000
